package wms.model;

import java.util.Date;

public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.product_id
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.product_cd
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    private String productCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.product_name
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.price
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    private Integer price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.cre_prg
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    private String crePrg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.cre_time
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    private Date creTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.upd_prg
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    private String updPrg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.upd_time
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    private Date updTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.remark
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.product_id
     *
     * @return the value of products.product_id
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.product_id
     *
     * @param productId the value for products.product_id
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.product_cd
     *
     * @return the value of products.product_cd
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    public String getProductCd() {
        return productCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.product_cd
     *
     * @param productCd the value for products.product_cd
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    public void setProductCd(String productCd) {
        this.productCd = productCd == null ? null : productCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.product_name
     *
     * @return the value of products.product_name
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.product_name
     *
     * @param productName the value for products.product_name
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.price
     *
     * @return the value of products.price
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.price
     *
     * @param price the value for products.price
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.cre_prg
     *
     * @return the value of products.cre_prg
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    public String getCrePrg() {
        return crePrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.cre_prg
     *
     * @param crePrg the value for products.cre_prg
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    public void setCrePrg(String crePrg) {
        this.crePrg = crePrg == null ? null : crePrg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.cre_time
     *
     * @return the value of products.cre_time
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    public Date getCreTime() {
        return creTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.cre_time
     *
     * @param creTime the value for products.cre_time
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    public void setCreTime(Date creTime) {
        this.creTime = creTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.upd_prg
     *
     * @return the value of products.upd_prg
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    public String getUpdPrg() {
        return updPrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.upd_prg
     *
     * @param updPrg the value for products.upd_prg
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    public void setUpdPrg(String updPrg) {
        this.updPrg = updPrg == null ? null : updPrg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.upd_time
     *
     * @return the value of products.upd_time
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    public Date getUpdTime() {
        return updTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.upd_time
     *
     * @param updTime the value for products.upd_time
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    public void setUpdTime(Date updTime) {
        this.updTime = updTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.remark
     *
     * @return the value of products.remark
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.remark
     *
     * @param remark the value for products.remark
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}