package wms.model;

import java.util.Date;

public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.product.product_id
     *
     * @mbg.generated Sat Dec 27 21:53:37 JST 2025
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.product.product_cd
     *
     * @mbg.generated Sat Dec 27 21:53:37 JST 2025
     */
    private String productCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.product.product_name
     *
     * @mbg.generated Sat Dec 27 21:53:37 JST 2025
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.product.price
     *
     * @mbg.generated Sat Dec 27 21:53:37 JST 2025
     */
    private Integer price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.product.cre_prg
     *
     * @mbg.generated Sat Dec 27 21:53:37 JST 2025
     */
    private String crePrg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.product.cre_time
     *
     * @mbg.generated Sat Dec 27 21:53:37 JST 2025
     */
    private Date creTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.product.upd_prg
     *
     * @mbg.generated Sat Dec 27 21:53:37 JST 2025
     */
    private String updPrg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.product.upd_time
     *
     * @mbg.generated Sat Dec 27 21:53:37 JST 2025
     */
    private Date updTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.product.remark
     *
     * @mbg.generated Sat Dec 27 21:53:37 JST 2025
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.product.product_id
     *
     * @return the value of public.product.product_id
     *
     * @mbg.generated Sat Dec 27 21:53:37 JST 2025
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.product.product_id
     *
     * @param productId the value for public.product.product_id
     *
     * @mbg.generated Sat Dec 27 21:53:37 JST 2025
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.product.product_cd
     *
     * @return the value of public.product.product_cd
     *
     * @mbg.generated Sat Dec 27 21:53:37 JST 2025
     */
    public String getProductCd() {
        return productCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.product.product_cd
     *
     * @param productCd the value for public.product.product_cd
     *
     * @mbg.generated Sat Dec 27 21:53:37 JST 2025
     */
    public void setProductCd(String productCd) {
        this.productCd = productCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.product.product_name
     *
     * @return the value of public.product.product_name
     *
     * @mbg.generated Sat Dec 27 21:53:37 JST 2025
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.product.product_name
     *
     * @param productName the value for public.product.product_name
     *
     * @mbg.generated Sat Dec 27 21:53:37 JST 2025
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.product.price
     *
     * @return the value of public.product.price
     *
     * @mbg.generated Sat Dec 27 21:53:37 JST 2025
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.product.price
     *
     * @param price the value for public.product.price
     *
     * @mbg.generated Sat Dec 27 21:53:37 JST 2025
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.product.cre_prg
     *
     * @return the value of public.product.cre_prg
     *
     * @mbg.generated Sat Dec 27 21:53:37 JST 2025
     */
    public String getCrePrg() {
        return crePrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.product.cre_prg
     *
     * @param crePrg the value for public.product.cre_prg
     *
     * @mbg.generated Sat Dec 27 21:53:37 JST 2025
     */
    public void setCrePrg(String crePrg) {
        this.crePrg = crePrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.product.cre_time
     *
     * @return the value of public.product.cre_time
     *
     * @mbg.generated Sat Dec 27 21:53:37 JST 2025
     */
    public Date getCreTime() {
        return creTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.product.cre_time
     *
     * @param creTime the value for public.product.cre_time
     *
     * @mbg.generated Sat Dec 27 21:53:37 JST 2025
     */
    public void setCreTime(Date creTime) {
        this.creTime = creTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.product.upd_prg
     *
     * @return the value of public.product.upd_prg
     *
     * @mbg.generated Sat Dec 27 21:53:37 JST 2025
     */
    public String getUpdPrg() {
        return updPrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.product.upd_prg
     *
     * @param updPrg the value for public.product.upd_prg
     *
     * @mbg.generated Sat Dec 27 21:53:37 JST 2025
     */
    public void setUpdPrg(String updPrg) {
        this.updPrg = updPrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.product.upd_time
     *
     * @return the value of public.product.upd_time
     *
     * @mbg.generated Sat Dec 27 21:53:37 JST 2025
     */
    public Date getUpdTime() {
        return updTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.product.upd_time
     *
     * @param updTime the value for public.product.upd_time
     *
     * @mbg.generated Sat Dec 27 21:53:37 JST 2025
     */
    public void setUpdTime(Date updTime) {
        this.updTime = updTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.product.remark
     *
     * @return the value of public.product.remark
     *
     * @mbg.generated Sat Dec 27 21:53:37 JST 2025
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.product.remark
     *
     * @param remark the value for public.product.remark
     *
     * @mbg.generated Sat Dec 27 21:53:37 JST 2025
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}