package wms.model;

import java.util.Date;

public class Receive {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receive.receive_id
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    private Long receiveId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receive.product_id
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receive.quantity
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receive.cre_prg
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    private String crePrg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receive.cre_time
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    private Date creTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receive.upd_prg
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    private String updPrg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receive.upd_time
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    private Date updTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receive.remark
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receive.receive_id
     *
     * @return the value of receive.receive_id
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    public Long getReceiveId() {
        return receiveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receive.receive_id
     *
     * @param receiveId the value for receive.receive_id
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    public void setReceiveId(Long receiveId) {
        this.receiveId = receiveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receive.product_id
     *
     * @return the value of receive.product_id
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receive.product_id
     *
     * @param productId the value for receive.product_id
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receive.quantity
     *
     * @return the value of receive.quantity
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receive.quantity
     *
     * @param quantity the value for receive.quantity
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receive.cre_prg
     *
     * @return the value of receive.cre_prg
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    public String getCrePrg() {
        return crePrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receive.cre_prg
     *
     * @param crePrg the value for receive.cre_prg
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    public void setCrePrg(String crePrg) {
        this.crePrg = crePrg == null ? null : crePrg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receive.cre_time
     *
     * @return the value of receive.cre_time
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    public Date getCreTime() {
        return creTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receive.cre_time
     *
     * @param creTime the value for receive.cre_time
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    public void setCreTime(Date creTime) {
        this.creTime = creTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receive.upd_prg
     *
     * @return the value of receive.upd_prg
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    public String getUpdPrg() {
        return updPrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receive.upd_prg
     *
     * @param updPrg the value for receive.upd_prg
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    public void setUpdPrg(String updPrg) {
        this.updPrg = updPrg == null ? null : updPrg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receive.upd_time
     *
     * @return the value of receive.upd_time
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    public Date getUpdTime() {
        return updTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receive.upd_time
     *
     * @param updTime the value for receive.upd_time
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    public void setUpdTime(Date updTime) {
        this.updTime = updTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receive.remark
     *
     * @return the value of receive.remark
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receive.remark
     *
     * @param remark the value for receive.remark
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}