package wms.model;

import java.util.Date;

public class Ship {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ship.ship_id
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    private Long shipId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ship.product_id
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ship.quantity
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ship.cre_prg
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    private String crePrg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ship.cre_time
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    private Date creTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ship.upd_prg
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    private String updPrg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ship.upd_time
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    private Date updTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ship.remark
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ship.ship_id
     *
     * @return the value of ship.ship_id
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    public Long getShipId() {
        return shipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ship.ship_id
     *
     * @param shipId the value for ship.ship_id
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    public void setShipId(Long shipId) {
        this.shipId = shipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ship.product_id
     *
     * @return the value of ship.product_id
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ship.product_id
     *
     * @param productId the value for ship.product_id
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ship.quantity
     *
     * @return the value of ship.quantity
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ship.quantity
     *
     * @param quantity the value for ship.quantity
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ship.cre_prg
     *
     * @return the value of ship.cre_prg
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    public String getCrePrg() {
        return crePrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ship.cre_prg
     *
     * @param crePrg the value for ship.cre_prg
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    public void setCrePrg(String crePrg) {
        this.crePrg = crePrg == null ? null : crePrg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ship.cre_time
     *
     * @return the value of ship.cre_time
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    public Date getCreTime() {
        return creTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ship.cre_time
     *
     * @param creTime the value for ship.cre_time
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    public void setCreTime(Date creTime) {
        this.creTime = creTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ship.upd_prg
     *
     * @return the value of ship.upd_prg
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    public String getUpdPrg() {
        return updPrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ship.upd_prg
     *
     * @param updPrg the value for ship.upd_prg
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    public void setUpdPrg(String updPrg) {
        this.updPrg = updPrg == null ? null : updPrg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ship.upd_time
     *
     * @return the value of ship.upd_time
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    public Date getUpdTime() {
        return updTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ship.upd_time
     *
     * @param updTime the value for ship.upd_time
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    public void setUpdTime(Date updTime) {
        this.updTime = updTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ship.remark
     *
     * @return the value of ship.remark
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ship.remark
     *
     * @param remark the value for ship.remark
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}