package wms.model;

import java.util.Date;

public class Stock {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stocks.stock_id
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    private Long stockId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stocks.product_id
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stocks.stock_qty
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    private Integer stockQty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stocks.cre_prg
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    private String crePrg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stocks.cre_time
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    private Date creTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stocks.upd_prg
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    private String updPrg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stocks.upd_time
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    private Date updTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stocks.remark
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stocks.stock_id
     *
     * @return the value of stocks.stock_id
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    public Long getStockId() {
        return stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stocks.stock_id
     *
     * @param stockId the value for stocks.stock_id
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    public void setStockId(Long stockId) {
        this.stockId = stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stocks.product_id
     *
     * @return the value of stocks.product_id
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stocks.product_id
     *
     * @param productId the value for stocks.product_id
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stocks.stock_qty
     *
     * @return the value of stocks.stock_qty
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    public Integer getStockQty() {
        return stockQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stocks.stock_qty
     *
     * @param stockQty the value for stocks.stock_qty
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    public void setStockQty(Integer stockQty) {
        this.stockQty = stockQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stocks.cre_prg
     *
     * @return the value of stocks.cre_prg
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    public String getCrePrg() {
        return crePrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stocks.cre_prg
     *
     * @param crePrg the value for stocks.cre_prg
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    public void setCrePrg(String crePrg) {
        this.crePrg = crePrg == null ? null : crePrg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stocks.cre_time
     *
     * @return the value of stocks.cre_time
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    public Date getCreTime() {
        return creTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stocks.cre_time
     *
     * @param creTime the value for stocks.cre_time
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    public void setCreTime(Date creTime) {
        this.creTime = creTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stocks.upd_prg
     *
     * @return the value of stocks.upd_prg
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    public String getUpdPrg() {
        return updPrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stocks.upd_prg
     *
     * @param updPrg the value for stocks.upd_prg
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    public void setUpdPrg(String updPrg) {
        this.updPrg = updPrg == null ? null : updPrg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stocks.upd_time
     *
     * @return the value of stocks.upd_time
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    public Date getUpdTime() {
        return updTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stocks.upd_time
     *
     * @param updTime the value for stocks.upd_time
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    public void setUpdTime(Date updTime) {
        this.updTime = updTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stocks.remark
     *
     * @return the value of stocks.remark
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stocks.remark
     *
     * @param remark the value for stocks.remark
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}