package wms.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class StockExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.stock
     *
     * @mbg.generated Sat Dec 27 21:53:37 JST 2025
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.stock
     *
     * @mbg.generated Sat Dec 27 21:53:37 JST 2025
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.stock
     *
     * @mbg.generated Sat Dec 27 21:53:37 JST 2025
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.stock
     *
     * @mbg.generated Sat Dec 27 21:53:37 JST 2025
     */
    public StockExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.stock
     *
     * @mbg.generated Sat Dec 27 21:53:37 JST 2025
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.stock
     *
     * @mbg.generated Sat Dec 27 21:53:37 JST 2025
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.stock
     *
     * @mbg.generated Sat Dec 27 21:53:37 JST 2025
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.stock
     *
     * @mbg.generated Sat Dec 27 21:53:37 JST 2025
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.stock
     *
     * @mbg.generated Sat Dec 27 21:53:37 JST 2025
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.stock
     *
     * @mbg.generated Sat Dec 27 21:53:37 JST 2025
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.stock
     *
     * @mbg.generated Sat Dec 27 21:53:37 JST 2025
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.stock
     *
     * @mbg.generated Sat Dec 27 21:53:37 JST 2025
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.stock
     *
     * @mbg.generated Sat Dec 27 21:53:37 JST 2025
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.stock
     *
     * @mbg.generated Sat Dec 27 21:53:37 JST 2025
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.stock
     *
     * @mbg.generated Sat Dec 27 21:53:37 JST 2025
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andStockIdIsNull() {
            addCriterion("stock_id is null");
            return (Criteria) this;
        }

        public Criteria andStockIdIsNotNull() {
            addCriterion("stock_id is not null");
            return (Criteria) this;
        }

        public Criteria andStockIdEqualTo(Long value) {
            addCriterion("stock_id =", value, "stockId");
            return (Criteria) this;
        }

        public Criteria andStockIdNotEqualTo(Long value) {
            addCriterion("stock_id <>", value, "stockId");
            return (Criteria) this;
        }

        public Criteria andStockIdGreaterThan(Long value) {
            addCriterion("stock_id >", value, "stockId");
            return (Criteria) this;
        }

        public Criteria andStockIdGreaterThanOrEqualTo(Long value) {
            addCriterion("stock_id >=", value, "stockId");
            return (Criteria) this;
        }

        public Criteria andStockIdLessThan(Long value) {
            addCriterion("stock_id <", value, "stockId");
            return (Criteria) this;
        }

        public Criteria andStockIdLessThanOrEqualTo(Long value) {
            addCriterion("stock_id <=", value, "stockId");
            return (Criteria) this;
        }

        public Criteria andStockIdIn(List<Long> values) {
            addCriterion("stock_id in", values, "stockId");
            return (Criteria) this;
        }

        public Criteria andStockIdNotIn(List<Long> values) {
            addCriterion("stock_id not in", values, "stockId");
            return (Criteria) this;
        }

        public Criteria andStockIdBetween(Long value1, Long value2) {
            addCriterion("stock_id between", value1, value2, "stockId");
            return (Criteria) this;
        }

        public Criteria andStockIdNotBetween(Long value1, Long value2) {
            addCriterion("stock_id not between", value1, value2, "stockId");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNull() {
            addCriterion("product_id is null");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNotNull() {
            addCriterion("product_id is not null");
            return (Criteria) this;
        }

        public Criteria andProductIdEqualTo(Long value) {
            addCriterion("product_id =", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotEqualTo(Long value) {
            addCriterion("product_id <>", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThan(Long value) {
            addCriterion("product_id >", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThanOrEqualTo(Long value) {
            addCriterion("product_id >=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThan(Long value) {
            addCriterion("product_id <", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThanOrEqualTo(Long value) {
            addCriterion("product_id <=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdIn(List<Long> values) {
            addCriterion("product_id in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotIn(List<Long> values) {
            addCriterion("product_id not in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdBetween(Long value1, Long value2) {
            addCriterion("product_id between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotBetween(Long value1, Long value2) {
            addCriterion("product_id not between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andStockQtyIsNull() {
            addCriterion("stock_qty is null");
            return (Criteria) this;
        }

        public Criteria andStockQtyIsNotNull() {
            addCriterion("stock_qty is not null");
            return (Criteria) this;
        }

        public Criteria andStockQtyEqualTo(Integer value) {
            addCriterion("stock_qty =", value, "stockQty");
            return (Criteria) this;
        }

        public Criteria andStockQtyNotEqualTo(Integer value) {
            addCriterion("stock_qty <>", value, "stockQty");
            return (Criteria) this;
        }

        public Criteria andStockQtyGreaterThan(Integer value) {
            addCriterion("stock_qty >", value, "stockQty");
            return (Criteria) this;
        }

        public Criteria andStockQtyGreaterThanOrEqualTo(Integer value) {
            addCriterion("stock_qty >=", value, "stockQty");
            return (Criteria) this;
        }

        public Criteria andStockQtyLessThan(Integer value) {
            addCriterion("stock_qty <", value, "stockQty");
            return (Criteria) this;
        }

        public Criteria andStockQtyLessThanOrEqualTo(Integer value) {
            addCriterion("stock_qty <=", value, "stockQty");
            return (Criteria) this;
        }

        public Criteria andStockQtyIn(List<Integer> values) {
            addCriterion("stock_qty in", values, "stockQty");
            return (Criteria) this;
        }

        public Criteria andStockQtyNotIn(List<Integer> values) {
            addCriterion("stock_qty not in", values, "stockQty");
            return (Criteria) this;
        }

        public Criteria andStockQtyBetween(Integer value1, Integer value2) {
            addCriterion("stock_qty between", value1, value2, "stockQty");
            return (Criteria) this;
        }

        public Criteria andStockQtyNotBetween(Integer value1, Integer value2) {
            addCriterion("stock_qty not between", value1, value2, "stockQty");
            return (Criteria) this;
        }

        public Criteria andCrePrgIsNull() {
            addCriterion("cre_prg is null");
            return (Criteria) this;
        }

        public Criteria andCrePrgIsNotNull() {
            addCriterion("cre_prg is not null");
            return (Criteria) this;
        }

        public Criteria andCrePrgEqualTo(String value) {
            addCriterion("cre_prg =", value, "crePrg");
            return (Criteria) this;
        }

        public Criteria andCrePrgNotEqualTo(String value) {
            addCriterion("cre_prg <>", value, "crePrg");
            return (Criteria) this;
        }

        public Criteria andCrePrgGreaterThan(String value) {
            addCriterion("cre_prg >", value, "crePrg");
            return (Criteria) this;
        }

        public Criteria andCrePrgGreaterThanOrEqualTo(String value) {
            addCriterion("cre_prg >=", value, "crePrg");
            return (Criteria) this;
        }

        public Criteria andCrePrgLessThan(String value) {
            addCriterion("cre_prg <", value, "crePrg");
            return (Criteria) this;
        }

        public Criteria andCrePrgLessThanOrEqualTo(String value) {
            addCriterion("cre_prg <=", value, "crePrg");
            return (Criteria) this;
        }

        public Criteria andCrePrgLike(String value) {
            addCriterion("cre_prg like", value, "crePrg");
            return (Criteria) this;
        }

        public Criteria andCrePrgNotLike(String value) {
            addCriterion("cre_prg not like", value, "crePrg");
            return (Criteria) this;
        }

        public Criteria andCrePrgIn(List<String> values) {
            addCriterion("cre_prg in", values, "crePrg");
            return (Criteria) this;
        }

        public Criteria andCrePrgNotIn(List<String> values) {
            addCriterion("cre_prg not in", values, "crePrg");
            return (Criteria) this;
        }

        public Criteria andCrePrgBetween(String value1, String value2) {
            addCriterion("cre_prg between", value1, value2, "crePrg");
            return (Criteria) this;
        }

        public Criteria andCrePrgNotBetween(String value1, String value2) {
            addCriterion("cre_prg not between", value1, value2, "crePrg");
            return (Criteria) this;
        }

        public Criteria andCreTimeIsNull() {
            addCriterion("cre_time is null");
            return (Criteria) this;
        }

        public Criteria andCreTimeIsNotNull() {
            addCriterion("cre_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreTimeEqualTo(Date value) {
            addCriterion("cre_time =", value, "creTime");
            return (Criteria) this;
        }

        public Criteria andCreTimeNotEqualTo(Date value) {
            addCriterion("cre_time <>", value, "creTime");
            return (Criteria) this;
        }

        public Criteria andCreTimeGreaterThan(Date value) {
            addCriterion("cre_time >", value, "creTime");
            return (Criteria) this;
        }

        public Criteria andCreTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("cre_time >=", value, "creTime");
            return (Criteria) this;
        }

        public Criteria andCreTimeLessThan(Date value) {
            addCriterion("cre_time <", value, "creTime");
            return (Criteria) this;
        }

        public Criteria andCreTimeLessThanOrEqualTo(Date value) {
            addCriterion("cre_time <=", value, "creTime");
            return (Criteria) this;
        }

        public Criteria andCreTimeIn(List<Date> values) {
            addCriterion("cre_time in", values, "creTime");
            return (Criteria) this;
        }

        public Criteria andCreTimeNotIn(List<Date> values) {
            addCriterion("cre_time not in", values, "creTime");
            return (Criteria) this;
        }

        public Criteria andCreTimeBetween(Date value1, Date value2) {
            addCriterion("cre_time between", value1, value2, "creTime");
            return (Criteria) this;
        }

        public Criteria andCreTimeNotBetween(Date value1, Date value2) {
            addCriterion("cre_time not between", value1, value2, "creTime");
            return (Criteria) this;
        }

        public Criteria andUpdPrgIsNull() {
            addCriterion("upd_prg is null");
            return (Criteria) this;
        }

        public Criteria andUpdPrgIsNotNull() {
            addCriterion("upd_prg is not null");
            return (Criteria) this;
        }

        public Criteria andUpdPrgEqualTo(String value) {
            addCriterion("upd_prg =", value, "updPrg");
            return (Criteria) this;
        }

        public Criteria andUpdPrgNotEqualTo(String value) {
            addCriterion("upd_prg <>", value, "updPrg");
            return (Criteria) this;
        }

        public Criteria andUpdPrgGreaterThan(String value) {
            addCriterion("upd_prg >", value, "updPrg");
            return (Criteria) this;
        }

        public Criteria andUpdPrgGreaterThanOrEqualTo(String value) {
            addCriterion("upd_prg >=", value, "updPrg");
            return (Criteria) this;
        }

        public Criteria andUpdPrgLessThan(String value) {
            addCriterion("upd_prg <", value, "updPrg");
            return (Criteria) this;
        }

        public Criteria andUpdPrgLessThanOrEqualTo(String value) {
            addCriterion("upd_prg <=", value, "updPrg");
            return (Criteria) this;
        }

        public Criteria andUpdPrgLike(String value) {
            addCriterion("upd_prg like", value, "updPrg");
            return (Criteria) this;
        }

        public Criteria andUpdPrgNotLike(String value) {
            addCriterion("upd_prg not like", value, "updPrg");
            return (Criteria) this;
        }

        public Criteria andUpdPrgIn(List<String> values) {
            addCriterion("upd_prg in", values, "updPrg");
            return (Criteria) this;
        }

        public Criteria andUpdPrgNotIn(List<String> values) {
            addCriterion("upd_prg not in", values, "updPrg");
            return (Criteria) this;
        }

        public Criteria andUpdPrgBetween(String value1, String value2) {
            addCriterion("upd_prg between", value1, value2, "updPrg");
            return (Criteria) this;
        }

        public Criteria andUpdPrgNotBetween(String value1, String value2) {
            addCriterion("upd_prg not between", value1, value2, "updPrg");
            return (Criteria) this;
        }

        public Criteria andUpdTimeIsNull() {
            addCriterion("upd_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdTimeIsNotNull() {
            addCriterion("upd_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdTimeEqualTo(Date value) {
            addCriterion("upd_time =", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeNotEqualTo(Date value) {
            addCriterion("upd_time <>", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeGreaterThan(Date value) {
            addCriterion("upd_time >", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("upd_time >=", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeLessThan(Date value) {
            addCriterion("upd_time <", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeLessThanOrEqualTo(Date value) {
            addCriterion("upd_time <=", value, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeIn(List<Date> values) {
            addCriterion("upd_time in", values, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeNotIn(List<Date> values) {
            addCriterion("upd_time not in", values, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeBetween(Date value1, Date value2) {
            addCriterion("upd_time between", value1, value2, "updTime");
            return (Criteria) this;
        }

        public Criteria andUpdTimeNotBetween(Date value1, Date value2) {
            addCriterion("upd_time not between", value1, value2, "updTime");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.stock
     *
     * @mbg.generated do_not_delete_during_merge Sat Dec 27 21:53:37 JST 2025
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.stock
     *
     * @mbg.generated Sat Dec 27 21:53:37 JST 2025
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}