package wms.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import wms.model.Product;
import wms.model.ProductExample;

public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.product
     *
     * @mbg.generated Sat Dec 27 14:07:42 JST 2025
     */
    long countByExample(ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.product
     *
     * @mbg.generated Sat Dec 27 14:07:42 JST 2025
     */
    int deleteByExample(ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.product
     *
     * @mbg.generated Sat Dec 27 14:07:42 JST 2025
     */
    int deleteByPrimaryKey(Long productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.product
     *
     * @mbg.generated Sat Dec 27 14:07:42 JST 2025
     */
    int insert(Product row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.product
     *
     * @mbg.generated Sat Dec 27 14:07:42 JST 2025
     */
    int insertSelective(Product row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.product
     *
     * @mbg.generated Sat Dec 27 14:07:42 JST 2025
     */
    List<Product> selectByExample(ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.product
     *
     * @mbg.generated Sat Dec 27 14:07:42 JST 2025
     */
    Product selectByPrimaryKey(Long productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.product
     *
     * @mbg.generated Sat Dec 27 14:07:42 JST 2025
     */
    int updateByExampleSelective(@Param("row") Product row, @Param("example") ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.product
     *
     * @mbg.generated Sat Dec 27 14:07:42 JST 2025
     */
    int updateByExample(@Param("row") Product row, @Param("example") ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.product
     *
     * @mbg.generated Sat Dec 27 14:07:42 JST 2025
     */
    int updateByPrimaryKeySelective(Product row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.product
     *
     * @mbg.generated Sat Dec 27 14:07:42 JST 2025
     */
    int updateByPrimaryKey(Product row);
}