package wms.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import wms.model.Receive;
import wms.model.ReceiveExample;

public interface ReceiveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receive
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    long countByExample(ReceiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receive
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    int deleteByExample(ReceiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receive
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    int deleteByPrimaryKey(Long receiveId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receive
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    int insert(Receive row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receive
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    int insertSelective(Receive row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receive
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    List<Receive> selectByExample(ReceiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receive
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    Receive selectByPrimaryKey(Long receiveId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receive
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    int updateByExampleSelective(@Param("row") Receive row, @Param("example") ReceiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receive
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    int updateByExample(@Param("row") Receive row, @Param("example") ReceiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receive
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    int updateByPrimaryKeySelective(Receive row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receive
     *
     * @mbg.generated Tue Dec 23 00:42:00 JST 2025
     */
    int updateByPrimaryKey(Receive row);
}