package wms.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import wms.model.Ship;
import wms.model.ShipExample;

public interface ShipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ship
     *
     * @mbg.generated Sat Dec 27 21:53:37 JST 2025
     */
    long countByExample(ShipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ship
     *
     * @mbg.generated Sat Dec 27 21:53:37 JST 2025
     */
    int deleteByExample(ShipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ship
     *
     * @mbg.generated Sat Dec 27 21:53:37 JST 2025
     */
    int deleteByPrimaryKey(Long shipId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ship
     *
     * @mbg.generated Sat Dec 27 21:53:37 JST 2025
     */
    int insert(Ship row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ship
     *
     * @mbg.generated Sat Dec 27 21:53:37 JST 2025
     */
    int insertSelective(Ship row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ship
     *
     * @mbg.generated Sat Dec 27 21:53:37 JST 2025
     */
    List<Ship> selectByExample(ShipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ship
     *
     * @mbg.generated Sat Dec 27 21:53:37 JST 2025
     */
    Ship selectByPrimaryKey(Long shipId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ship
     *
     * @mbg.generated Sat Dec 27 21:53:37 JST 2025
     */
    int updateByExampleSelective(@Param("row") Ship row, @Param("example") ShipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ship
     *
     * @mbg.generated Sat Dec 27 21:53:37 JST 2025
     */
    int updateByExample(@Param("row") Ship row, @Param("example") ShipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ship
     *
     * @mbg.generated Sat Dec 27 21:53:37 JST 2025
     */
    int updateByPrimaryKeySelective(Ship row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ship
     *
     * @mbg.generated Sat Dec 27 21:53:37 JST 2025
     */
    int updateByPrimaryKey(Ship row);
}