package wms.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import wms.model.Stock;
import wms.model.StockExample;

public interface StockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.stock
     *
     * @mbg.generated Sat Dec 27 14:07:42 JST 2025
     */
    long countByExample(StockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.stock
     *
     * @mbg.generated Sat Dec 27 14:07:42 JST 2025
     */
    int deleteByExample(StockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.stock
     *
     * @mbg.generated Sat Dec 27 14:07:42 JST 2025
     */
    int deleteByPrimaryKey(Long stockId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.stock
     *
     * @mbg.generated Sat Dec 27 14:07:42 JST 2025
     */
    int insert(Stock row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.stock
     *
     * @mbg.generated Sat Dec 27 14:07:42 JST 2025
     */
    int insertSelective(Stock row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.stock
     *
     * @mbg.generated Sat Dec 27 14:07:42 JST 2025
     */
    List<Stock> selectByExample(StockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.stock
     *
     * @mbg.generated Sat Dec 27 14:07:42 JST 2025
     */
    Stock selectByPrimaryKey(Long stockId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.stock
     *
     * @mbg.generated Sat Dec 27 14:07:42 JST 2025
     */
    int updateByExampleSelective(@Param("row") Stock row, @Param("example") StockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.stock
     *
     * @mbg.generated Sat Dec 27 14:07:42 JST 2025
     */
    int updateByExample(@Param("row") Stock row, @Param("example") StockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.stock
     *
     * @mbg.generated Sat Dec 27 14:07:42 JST 2025
     */
    int updateByPrimaryKeySelective(Stock row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.stock
     *
     * @mbg.generated Sat Dec 27 14:07:42 JST 2025
     */
    int updateByPrimaryKey(Stock row);
}